### ISSUE TITLE
This can be shortened

### ISSUE THREAD

**Issue by elpres** [courtiol/judsound#10]
Instead of
```python
                if button_index == 0:
                    self.clock.set_alarm(add = [1, 0, 0, 0])
                elif button_index == 1:
                    self.clock.set_alarm(add = [0, 1, 0, 0])
                elif button_index == 2:
                    self.clock.set_alarm(add = [0, 0, 1, 0])
                elif button_index == 3:
                    self.clock.set_alarm(add = [0, 0, 0, 1])
```
Why not
```python
                delta = [0, 0, 0, 0]
                delta[button_index] = 1
                self.clock.set_alarm(add=delta)
````

**Comment by elpres** [comment]
Overall though, the way the alarm is adjusted feels over-engineered. I know having a shiny general solution feels nice, but realistically, all that will ever happen is that you'll be incrementing a single digit by 1. So instead of making an almost entirely empty "vector" here, and then doing the complicated iteration over two lists in `Clock.set_alarm`, why not simply do this:
```python
self.clock.alarm[button_index] = (self.clock.alarm[button_index] + 1) % [3, 10, 6, 10][button_index]
```

That's the same functionality in one line, and you can get rid of `Clock.set_alarm` as well. Maybe break it up into several lines for clarity.

**Comment by courtiol** [comment]
good catch...
