### ISSUE TITLE
File filter without using regexes

### ISSUE THREAD

**Issue by elpres** [courtiol/judsound#22]
https://github.com/courtiol/judsound/blob/258839d710f2cdfc1e9357c179c5ce711fd1715b/python/judsound_player.py#L27

Not sure whether you already learned about the ability to filter inside a list comprehension:
```python
        self.tracks_files = [file for file in files_in_path_music if file.endswith('mp3') or file.endswith('wav')]
```
The comment below there mentions that filenames should start with a number, which this test doesn't detect, but neither does the regex in the original code.

**Comment by courtiol** [comment]
```py
>>> files_in_path_music = ["1_bla.mp3", "toto.mp3", "2_bli.wav", "3_foo"]
>>> self.tracks_files = [file for file in files_in_path_music if file.endswith('mp3') or file.endwith('wav')]
AttributeError: 'str' object has no attribute 'endwith'
```

**Comment by elpres** [comment]
Sorry, it's `.endswith()`, with an "s" in the middle

**Comment by courtiol** [comment]
Can it understand regex?

```py
>>> files_in_path_music = ["1_bla.mp3", "toto.mp3", "2_bli.wav", "3_foo"]
>>> tracks_files = [file for file in files_in_path_music if file.startswith('\d') and (file.endswith('mp3') or file.endswith('wav'))]
>>> tracks_files
[]
```

**Comment by elpres** [comment]
Nope, just literal strings.
