### ISSUE TITLE
This function shouldn't be an instance method

### ISSUE THREAD

**Issue by elpres** [courtiol/judsound#3]
Since "self" isn't used anywhere inside it, it should either be free function or a class method, if you prefer to bind it to the class

https://github.com/courtiol/judsound/blob/ca668862083b163ad23cd025d974bf37d38f6dbd/python/main.py#L125

**Comment by courtiol** [comment]
My understanding is that in this case it should be more a static method than a class method, please correct me if I am wrong.

**Comment by elpres** [comment]
Right, static method is correct here. Had to look it up myself because I only use classes if I can't avoid it, and don't know all the details of object-oriented programming in Python. This is probably more a question of personal taste, but I would have turned this method into a stand-alone function.
